name: CI

on:
  push:
    branches: [master]
    paths-ignore: [docs/**]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    concurrency: deploy-step  # Only one deploy job at any time
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-deploy') && !contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/master' }}
    steps:
      - name: Execute deploy command
        uses: appleboy/ssh-action@v1
        # Enable Buildkit and let compose use it to speed up image building
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          envs: DOCKER_BUILDKIT,COMPOSE_DOCKER_CLI_BUILD
          script: |
            set -euo pipefail

            mkdir -p mcpc-online-judge
            cd mcpc-online-judge
            cd repo/.. || git clone https://github.com/MonashAPS/mcpc-online-judge.git repo
            cd repo/
            sudo rm -rf dmoj/repo

            git pull
            git submodule update --init --recursive

            rm dmoj/environment/*
            echo '${{ secrets.ENV_MYSQL }}' | base64 -d > dmoj/environment/mysql.env
            echo '${{ secrets.ENV_MYSQL_ADMIN }}' | base64 -d > dmoj/environment/mysql-admin.env
            echo '${{ secrets.ENV_SITE }}' | base64 -d > dmoj/environment/site.env

            cd dmoj
            sudo ./scripts/run_all
